### PR TITLE
fix: columns property align not work

### LINKED ISSUE #264: 1.16.1版本设置不了列的对齐方式
## Describe the bug
修改columns 或者operationAttrs中的align不起作用，最新版本出现

### PR DESCRIPTION
**Pull request by lianghx-319**
CLOSE #264 

## Why
- multi-level-header should align center but should not affect normal header
- fix issue #264

## How
create a computed property to define if multi-level header or not

if yes, render columns with align center
if not, render columns as before

More importantly, columns property can assign the computed property

## Test
after
image

image

### CODE REVIEW

File: src/el-data-table.vue [hunk 1]
```diff
@@ -773,6 +781,16 @@ export default {
     }
   },
   computed: {
+    hasSelect() {
+      return this.columns.length && this.columns[0].type == 'selection'
+    },
+    columnsAlign() {
+      if (this.columns.some(col => col.columns && col.columns.length)) {
```
Comment (levy9527) [inline src/el-data-table.vue]: 加个注意：多级表头默认居中

File: src/components/el-data-table-column.js [hunk 2]
```diff
@@ -1,20 +1,17 @@
-const defaultAttrs = {
-  align: 'center'
-}
 export default {
   name: 'el-data-table-column',
   functional: true,
   render(h, {data, props}) {
     let children = []
+    const align = props.align
```
Comment (levy9527) [inline src/components/el-data-table-column.js]: 是否有点多余。。。

Comment (lianghx-319) [reply src/components/el-data-table-column.js]: 需要继续传才能保持后面的 columns 也是居中的
